### ISSUE TITLE
Are minified names determanistic?

### ISSUE THREAD

**Issue by KyleAMathews** [stldo/gatsby-plugin-minify-classnames#3] opened 2021-09-14 18:22 UTC
I was looking into an issue with a Gatsby site using this plugin and they had one build that worked and then the next build, their CSS was broken. The second build used the cached css from the previous build I believe as the inlined css was the same for both but the classNames inside the react components for the second build was different. So it looks like webpack thought the CSS hadn't changed (because it hadn't) so didn't write out a new CSS file but this plugin still created different class names.

**Comment by stldo** [comment] 2021-09-14 20:51
Hi! Thanks for sharing your issue. Actually, this plugin uses an internal cache associating the `resourcePath` and `localName` returned by webpack to fragments used to create the local ident. In other words, if you have a file called `bar.css`, its minified class names will always start with `b_` — a following file called `foo.css` will always be `c_` and so on. The second part of the minified ident comes from the local class name. So, if you have a `.button` inside `bar.css`, the minified class name will be `b_b`; `.form` will be `b_c` and so on. The cached fragments for class names are shared between files, so `.form` inside `bar.css` will be `c_c`, while `.modal` will be `c_d`.

In theory, if the files are exactly the same, and their content hadn't changed, this plugin should always return the same results. The only thing it modifies is webpack `getLocalIdent` configuration, so it should be executed only when webpack requests idents. I can think about a couple of possible reasons for this issue, but I'll need a little more info in order to help you. About the different class names in the second build, are you referring to the minified class names, right? Considering the fragments of the minified class name — i.e. `b_b` as `pathFragment_localNameFragment` —, which part is changing, `pathFragment`, `localNameFragment` or both? Are you using other plugins that modify webpack configuration or change the CSS files?

**Comment by KyleAMathews** [comment] 2021-09-14 22:20
This is the generated HTML — https://gist.github.com/KyleAMathews/599fc42cf6c541311b4186a3ac6861c8

I don't have all information as this is a customer site on Gatsby Cloud but I do know they're using gatsby-plugin-sass. cc @daniellangnet who's working on the site

**Comment by daniellangnet** [comment] 2021-09-14 22:32
Thanks @KyleAMathews!

@stldo I gave you read account to our internal repository `mt-www` (no secrets there) where you can see the full `package.json` and other details of how we had your plugin configured (prior to the last commit where we removed it)

Let me know if anything else would be helpful. Thanks so much for your work with this plugin!

**Comment by stldo** [comment] 2021-09-15 02:45
@daniellangnet, thanks for the information. I've checked the repository and I couldn't find something that would interfere with this plugin. Furthermore, I've cloned the repository and I couldn't find any related issues. Either running `gatsby develop` command followed by `gatsby build`, or two consecutive `gatsby build` commands, hadn't broken the CSS. Could you please share the steps to reproduce the issue?

**Comment by daniellangnet** [comment] 2021-09-15 17:29
@stldo thanks so much for looking into this, I really appreciate the effort!

Unfortunately I don't have steps to reproduce. What happened is that we've been using Gatsby Cloud as well as this plugin, and everything was fine for a long time. Then, seemingly out of nowhere, a regular content update from Contentful that triggered an incremental build broke the CSS, as it was described above. There weren't any build error messages or anything unusual, so it got deployed and took us over an hour to notice. This is when we reached out to Gatsby Cloud support, Kyle investigated, and now we're here :)

Gatsby Cloud keeps a record of all the builds, logs, and the output files. If you like to keep investigating this more, I could give you access there and you could look at the two subsequent builds during which it broken. If so, I'd need your email address for the invite (you could send it to me at daniel@mangomint.com). 

Totally understand if this goes too far however and you want to close the issue here instead. Thanks again for all your work!

**Comment by stldo** [comment] 2021-09-17 03:43
@daniellangnet there's a good chance that it's an issue with Gatsby cache, try to clear it and do a manual deployment. If that doesn't work, I'm afraid that the logs will not have much useful information, as it seems that the build didn't generate any errors. Please let me know if you tested clearing the cache and if it worked. Thank you very much for your time and all the information.

**Comment by daniellangnet** [comment] 2021-09-17 17:19
@stldo Thanks! clearing the cache and rebuilding fixed the issue immediately when it occurred. The problem is that almost an hour went by where it was broken (no errors, or other things that would've allowed us to catch it at build time), which is a bit too long for us. Since there is a risk that it happens again randomly, we have removed the plugin for now. Thanks again for your work on this! Feel free to close this

**Comment by stldo** [comment] 2021-09-18 01:34
@daniellangnet I see. I'm having some issues with recent versions of Gatsby, mainly due to their premature adoption of webpack persistent cache. Gatsby is a great tool, I use it for most websites I create, but we're porting a few websites to Next.js due to minor issues that aren't acceptable in a critical project. I hope that v4 will be more stable. Thank you for your willingness to help!

**Closed as completed by stldo** 2021-09-18 01:34 UTC

**Comment by KyleAMathews** [comment] 2021-09-18 06:34
@stldo what issues with webpack's cache? We've received no bug reports. If there's an issue, please report it!
